apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-account-server
  labels:
    {{- include "sdisk.labels" . | nindent 4 }}
    app.kubernetes.io/component: account-server
spec:
  replicas: {{ .Values.accountServer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: account-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: account-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: account-server
          image: {{ .Values.accountServer.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.accountServer.service.port }}
          env:
            {{- range $key, $val := .Values.accountServer.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: account-server
  labels:
    {{- include "sdisk.labels" . | nindent 4 }}
    app.kubernetes.io/component: account-server
spec:
  type: {{ .Values.accountServer.service.type }}
  selector:
    app.kubernetes.io/component: account-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.accountServer.service.port }}
      targetPort: {{ .Values.accountServer.service.port }}
      protocol: TCP
      name: http
