apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin-web
  labels:
    {{- include "sdisk.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-web
spec:
  replicas: {{ .Values.adminWeb.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: admin-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admin-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: admin-web
          image: {{ .Values.adminWeb.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.adminWeb.service.port }}
          env:
            {{- range $key, $val := .Values.adminWeb.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: admin-web
  labels:
    {{- include "sdisk.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-web
spec:
  type: {{ .Values.adminWeb.service.type }}
  selector:
    app.kubernetes.io/component: admin-web
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.adminWeb.service.port }}
      targetPort: {{ .Values.adminWeb.service.port }}
      protocol: TCP
      name: http
