{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    {{- range $key, $val := .Values.ingress.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.webHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: {{ .Values.web.service.port }}
          - path: /oauth
            pathType: Prefix
            backend:
              service:
                name: account-server
                port:
                  number: {{ .Values.accountServer.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: management-server
                port:
                  number: {{ .Values.managementServer.service.port }}
    - host: {{ .Values.ingress.adminHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-web
                port:
                  number: {{ .Values.adminWeb.service.port }}
    - host: {{ .Values.ingress.mcpHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-server
                port:
                  number: {{ .Values.mcpServer.service.port }}
{{- end }}
