apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-management-server
  labels:
    {{- include "sdisk.labels" . | nindent 4 }}
    app.kubernetes.io/component: management-server
spec:
  replicas: {{ .Values.managementServer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: management-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: management-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: management-server
          image: {{ .Values.managementServer.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.managementServer.service.port }}
          env:
            {{- range $key, $val := .Values.managementServer.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            - name: storage
              mountPath: /data/storage
      volumes:
        - name: storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: management-server
  labels:
    {{- include "sdisk.labels" . | nindent 4 }}
    app.kubernetes.io/component: management-server
spec:
  type: {{ .Values.managementServer.service.type }}
  selector:
    app.kubernetes.io/component: management-server
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.managementServer.service.port }}
      targetPort: {{ .Values.managementServer.service.port }}
      protocol: TCP
      name: http
